### ISSUE TITLE
when you release ver v2.0.8 ?

### ISSUE THREAD

**Issue by tinamore** [CHERTS/esp8266-devkit#10]
Hi
Thank for great project.
Can you tell me when you release v2.0.8 download for windows in http://programs74.ru/udkew-en.html ?

**Comment by fvpalha** [comment]
+1.

**Comment by CHERTS** [comment]
Released version 2.0.8 is planned for this weekend.

**Comment by flexiti** [comment]
with the latest SDK 1.3.0 ?

ps. Can You add http://bbs.espressif.com/viewtopic.php?p=3221  ? :)  eg. for LWIP debug propouse

**Comment by CHERTS** [comment]
Espressif SDK v1.3.0 is already added to the repository, see the last commit 7eb75a94c4f4668b5bac9cae24e40a300ef58266

**Comment by flexiti** [comment]
Can You update lwip demo with  http://bbs.espressif.com/viewtopic.php?p=3221  ?

**Comment by tinamore** [comment]
A Big Thanks for CHERTS.

**Comment by fvpalha** [comment]
I wait anxiously the next revision. Thanks and congratulations @CHERTS .
