### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by crosofg** [CHERTS/esp8266-devkit#14]
Hi 
I tried compiling the mesh light example. How do  i get past this error? what needs to be included  in the makefile?
CC espfs/espfs.c
Assembler messages:
Fatal error: can't create build/espfs/espfs.o: No such file or directory
make[2]: *** [build/espfs/espfs.o] Error 1
Thanks

**Comment by CHERTS** [comment]
Create a directory
C:/Espressif/examples/esp_mesh_sdk_app_light/app/libesphttpd/build/core
C:/Espressif/examples/esp_mesh_sdk_app_light/app/libesphttpd/build/espfs
C:/Espressif/examples/esp_mesh_sdk_app_light/app/libesphttpd/build/util
and repeat build
