### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by crosofg** [CHERTS/esp8266-devkit#15]
Hi 
Upon compiling the mesh example I am receiving the following error.
c:/espressif/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: cannot find -lmgcc
collect2.exe: error: ld returned 1 exit status

What needs to be done here?

**Comment by CHERTS** [comment]
Replace in C:/Espressif/examples/esp_mesh_sdk_app_light/app/Makefile 
-lmgcc
on
-lgcc
