### ISSUE TITLE
.irom0.text will not fit. mesh Example

### ISSUE THREAD

**Issue by crosofg** [CHERTS/esp8266-devkit#16]
Hi upon compiling I am gettting following error.

/xtensa-lx106-elf/bin/ld.exe: .output/eagle/release/image/eagle.app.v6.out section `.irom0.text' will not fit in region `irom0_0_seg'

Is this due to limited flash size? I have 512KB  flash. What is the minimum flash size required to run esp mesh example?
Thanks

**Comment by CHERTS** [comment]
I do not have any information for which the size of flash is designed Mesh SDK. This SDK is in beta stage and may not work correctly.
