### ISSUE TITLE
Add the rboot sample in package

### ISSUE THREAD

**Issue by fvpalha** [CHERTS/esp8266-devkit#17]
Hi Mikhail,

I suggest add the FOTA example with [rboot](https://github.com/raburton/esp8266).

I use the [UDK](https://github.com/CHERTS/esp8266-devkit) in our project and I am having trouble with the Makefile with [rboot](https://github.com/raburton/esp8266).

Your help would be great.

Kind regards.

**Comment by fvpalha** [comment]
Hi Mikhail,

I commited the sample in my fork [esp8266-devkit](https://github.com/fvpalha/esp8266-devkit/commit/832db9e4049766a216e30c44321721e87737c109).

Kind regards.

**Comment by CHERTS** [comment]
Hi
a very good example, I am ready to accept in devkit, please, create a pull
requests.

2015-09-28 22:40 GMT+05:00 Fernando Vilmar Palha <notifications@github.com>:

> Hi Mikhail,
>
> I commited the sample in my fork esp8266-devkit
> <https://github.com/fvpalha/esp8266-devkit/commit/832db9e4049766a216e30c44321721e87737c109>
> .
>
> Kind regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CHERTS/esp8266-devkit/issues/17#issuecomment-143816423>
> .
>



-- 
--------------------------------------------------------------------------
С наилучшими пожеланиями, Михаил Григорьев
Руководитель группы разработчиков
--------------------------------------------------------------------------
Россия
г. Челябинск
WWW: www.novell.chel.ru
WWW: www.im-history.ru
WWW: www.programs74.ru
E-Mail: sleuthhound@gmail.com
ICQ: 161867489
--------------------------------------------------------------------------
With the best regards, Mikhail Grigorev
Lead developer
--------------------------------------------------------------------------
Russia
Chelyabinsk
WWW: www.novell.chel.ru
WWW: www.im-history.ru
WWW: www.programs74.ru
E-Mail: sleuthhound@gmail.com
ICQ: 161867489
--------------------------------------------------------------------------

**Comment by fvpalha** [comment]
Hi Mikhail,

I created the [pull request](https://github.com/CHERTS/esp8266-devkit/pull/18).

If possible, I would like your help to change the Makefile.

**Comment by CHERTS** [comment]
Thank Fernando, good work.
