### ISSUE TITLE
Why some macros are missing from SDK 1.2 ?

### ISSUE THREAD

**Issue by Picatek** [CHERTS/esp8266-devkit#20]
The following makros can be found in eagle_soc.h SDK 1.0.1 but not in SDK(latest) 1.2
`#define PIN_PULLDWN_DIS(PIN_NAME)             CLEAR_PERI_REG_MASK(PIN_NAME, PERIPHS_IO_MUX_PULLDWN)`
`#define PIN_PULLDWN_EN(PIN_NAME)              SET_PERI_REG_MASK(PIN_NAME, PERIPHS_IO_MUX_PULLDWN)`

**Comment by MrZANE42** [comment]
As far as I know there are no pull-downs in the chip, that's why they we're removed.
(Btw. latest SDK is 1.4)
