### ISSUE TITLE
Please, help me change the files/folders and the Makefile

### ISSUE THREAD

**Issue by fvpalha** [CHERTS/esp8266-devkit#21]
Hi Mikhail,

I would like to change the files/folders and the Makefile. Something like the others examples (user/drive/include) to make easy add the FOTA resource.

I changed the files/folders model in [rboot-sampleproject](https://github.com/fvpalha/esp8266-devkit/tree/master/Espressif/examples/rboot-sampleproject)

Now, it's necessary change the makefile to build the ROM.bin, the original Makefile was renamed to Makefile_original.

Your help would be great.

**Comment by CHERTS** [comment]
I added rBoot in the examples, see commit https://github.com/CHERTS/esp8266-devkit/commit/2ab80464549279f6c54e51ff62ddcc2aed14f4d2
