### ISSUE TITLE
CHERTS/esp8266-devkit - Sming

### ISSUE THREAD

**Issue by flexiti** [CHERTS/esp8266-devkit#22]
@CHERTS 
Can You give me Your comment on this please ? thanks :)

https://github.com/SmingHub/Sming/issues/332

btw. When will be ready 2.0.9 installator exe file for windows ? :)

**Comment by CHERTS** [comment]
rBoot compiles without problems in the DevKit 2.0.8
You can see an example rBoot-OTA from the catalog https://github.com/CHERTS/esp8266-devkit/tree/master/Espressif/examples/rboot-sampleproject

**Comment by flexiti** [comment]
ok, I compare and look for differences. Thank you
