### ISSUE TITLE
mkdir -p in makefiles does not work on windows

### ISSUE THREAD

**Issue by greg-ware** [CHERTS/esp8266-devkit#24]
I have this issue in several makefiles that try to make the build/driver and build/user directories.
The make runs mkdir -p with a forward-slash directory path and that does not work.

Making the dir manually lets the make complete ok.

Question is whether it is supposed to be a mkdir command in MinGW (mine does not have any)

Thanks,

Greg

**Comment by CHERTS** [comment]
I checked and mkdir -p working correctly the windows in the Makefile

In file examples\hello_world\Makefile I wrote:

$ (FW_BASE):
$ (Q) mkdir -p $ @
$ (Q) mkdir -p $ @ / test / test1 / test2

to make the build process were created directories and subdirectories firmware/test/test1/test2
