### ISSUE TITLE
CPU_CLK_FREQ' undeclared 

### ISSUE THREAD

**Issue by crosofg** [CHERTS/esp8266-devkit#25]
timers.c:392:51: error: 'CPU_CLK_FREQ' undeclared (first use in this function)

Where should this be declared?

**Comment by CHERTS** [comment]
I've updated the example lwip_open_demo_app, see commit https://github.com/CHERTS/esp8266-devkit/commit/faacc2177a19fccb522060f7534e76b92652dc7f

Use only Espressif SDK v1.4.0 or or higher
