### ISSUE TITLE
SHA1 implementation

### ISSUE THREAD

**Issue by crosofg** [CHERTS/esp8266-devkit#26]
Hi I want to use SHA function in the UDK. https://github.com/esp8266/Arduino/tree/master/libraries/Hash/src/sha1

I copied the .c and .h files in the user folder. what changes needs to be made in the makefile? 
I always get 
```
user/user_main.c:121: undefined reference to `sha1'
build/app_app.a(user_main.o): In function `user_init':
```

**Comment by flexiti** [comment]
did you added #include sha1.h in Your app_app ?

**Comment by crosofg** [comment]
yes i did.
