### ISSUE TITLE
ESP32 Toolchain support

### ISSUE THREAD

**Issue by hreintke** [CHERTS/esp8266-devkit#28]
Hi,
I am active in the Sming framework and there is currently work in progress to include ESP32 support in there.
For ESP8266 the windows users of sming are using Cherts UDK as a base for their development environment.

Are there any plans for adding the ESP32 toolchain for windows to the UDK releases ?
If so, can you indicate the progress you have in that and, if possible, any timelines on that ?

**Comment by robotiko** [comment]
+10

**Comment by CHERTS** [comment]
Development Unofficial DevKit for ESP 32 is almost finished, you can try the first [beta-version](http://programs74.ru/get.php?file=EspressifESP32DevKit).
It can be set and used in conjunction with Unofficial DevKit ESP8266.
While there is only one example - esp32_hello_world
I can not check to stitch this example, I have no board ESP32.

**Comment by flexiti** [comment]
and ESP32 is somewhere to buy?

**Comment by hreintke** [comment]
Thanks,
I took the beta version and successfully compiled the hello_world example.
Appreciate your work on this, will use this for my ESP32 Sming support and feedback results.

**Comment by CHERTS** [comment]
>>and ESP32 is somewhere to buy?
I do not know where to buy a ESP 32, it has not yet sold. I do not have it :(
