### ISSUE TITLE
Update esptool to newer version

### ISSUE THREAD

**Issue by valkuc** [CHERTS/esp8266-devkit#33]
It would be nice if you update ESPTOOL to newer version - https://github.com/themadinventor/esptool
I'm currently using 1.0.2 (already outdated) but anyway, it allows to use upload speeds more than 115200 bauds. For example, using FTDI, I am able to upload firmware at 921600 bauds.

**Comment by CHERTS** [comment]
Hi
in the next release I will update esptool.

**Comment by CHERTS** [comment]
esptool updated in DevKit v2.2.0, see http://programs74.ru/udkew-en.html
