### ISSUE TITLE
sysinfo example is broken

### ISSUE THREAD

**Issue by davydnorris** [CHERTS/esp8266-devkit#34]
For the past day I've been chasing what I believed was a problem with my toolchain or how I was flashing the chip, and it turned out to be a minor issue with the sysinfo example program.

The list of flash mode strings at the top are missing some commas, so the second half of them end up concatenating together and the array size becomes 4, not 6 :-)

Tiny error, but it means my 4M chips kept printing <null> for the mode no matter what I was doing, until I saw the missing punctuation

**Comment by CHERTS** [comment]
Fixed in commit https://github.com/CHERTS/esp8266-devkit/commit/a6907a6cc61754ca1eb7c5492971d20e400f4bbe
