### ISSUE TITLE
Incorrect memory setting in makefiles

### ISSUE THREAD

**Issue by davydnorris** [CHERTS/esp8266-devkit#36]
esp8266-devkit/Espressif/examples/ESP8266/common_nonos.mk has an incorrect setting for flash mode 6 on line 109.

It should read '32m-c1' but currently reads '32m' so ends up building for mode 6 (1024+1024) but only flashing mode 4 (512+512)

**Comment by CHERTS** [comment]
Hi, thank you.

Fixed in https://github.com/CHERTS/esp8266-devkit/commit/6712815a430b23b665d949aca369c9f91c5a7d16
