### ISSUE TITLE
Find out UDK version

### ISSUE THREAD

**Issue by ADiea** [CHERTS/esp8266-devkit#38]
Hi Is there a way to find the UDK version at make time? 

Recently the tools folder is moved to utils/ESP8266 and on older UDK the tols like esptool was in utils/

We need a way (registry, environment variable etc) to find out the UDK version in order to automatically adjust some paths. Is this implemented now? Will it be implemented in the future? A simple ESP_UDK_VERSION environment variable would be more than welcome.

**Comment by CHERTS** [comment]
UDK does not store anywhere version information.
In UDK v2.2.2 i will add the file C:\Espressif\version which will contain the version of UDK.
