### ISSUE TITLE
Hi, I really need help with this error .text' will not fit in regioniram1_0_seg'". I added Petit FAT  from http://elm-chan.org/fsw/ff/00index_p.html to drive a SD card but after solve all the compiler error this is persistant error. The binary file is 197 k and only 4 k more than original ESP-mqtt binary file.

### ISSUE THREAD

**Issue by Smith1966** [CHERTS/esp8266-devkit#4]

**Comment by fvpalha** [comment]
Hi @Smith1966.
The project [FatFs - Generic FAT File System Module](http://elm-chan.org/fsw/ff/00index_e.html) is really interesting.
Maybe the [ChaN](mailto:user1@elm-chan.org) can help you.
Please, keep us updated.

**Comment by CHERTS** [comment]
Do not make issue again, only one.
https://github.com/CHERTS/esp8266-devkit/issues/3
