### ISSUE TITLE
Experimenting with a new version

### ISSUE THREAD

**Issue by icodk** [CHERTS/esp8266-devkit#44]
I am using an old version of the devkit and it works fine. I would like to experiment with the newest version so I renamed the c:\Espressif folder to  c:\Espressif_ 
However when I try to run the installation of the newest devkit (Espressif-ESP8266-DevKit-v2.2.1-x86) I get the following message:
An old version of Unofficial Development Kit for Espressif ESP8266 was detected. Do you want to uninstall it ?
If I click No the new devkit is not installed
How can I have both installed ?

**Comment by cherts** [comment]
1. Copy c:\Espressif to c:\Espressif_OLD
2. Remove older DevKit
3. Install the new version DevKit
4. Change settings in file 
c:\Espressif_OLD\utils\ESP8266\gen_appbin.py
c:\Espressif_OLD\utils\ESP8266\gen_appbin_old.py
replace
cmd = 'C:\\Espressif....
on
cmd = 'C:\\Espressif_OLD
5. Run script
c:\Espressif_OLD\utils\ESP8266\py2exe_gen_appbin.cmd
and
c:\Espressif_OLD\utils\ESP8266\py2exe_gen_appbin_old.cmd
6. Change path in file c:\Espressif_OLD\utils\ESP8266\udkvars.bat 
replace
@set devkit_dir=C:\Espressif
on
@set devkit_dir=C:\Espressif_OLD
7. Change path in file C:\Espressif\examples\ESP8266\settings.mk
replace
XTENSA_TOOLS_ROOT ?= c:/Espressif/xtensa-lx106-elf/bin
SDK_BASE	?= c:/Espressif/ESP8266_SDK
SDK_TOOLS	?= c:/Espressif/utils/ESP8266
EXTRA_BASE	?= c:/Espressif/extra
on
XTENSA_TOOLS_ROOT ?= c:/Espressif_OLD/xtensa-lx106-elf/bin
SDK_BASE	?= c:/Espressif_OLD/ESP8266_SDK
SDK_TOOLS	?= c:/Espressif_OLD/utils/ESP8266
EXTRA_BASE	?= c:/Espressif_OLD/extra
8. Compile example firmware.
