### ISSUE TITLE
Где взять заголовочные файлы?

### ISSUE THREAD

**Issue by bondyara** [CHERTS/esp8266-devkit#45]
При попытке сборки примеров, возникают ошибки: string.h: No such file or directory
В include SDK нет файлов stdint.h, string.h и некоторых других.
Эти файлы можно найти только в SDK v0.9. Подключение файлов из старого SDK ни к чему не привели. Идут дальнейшие ошибки.

**Comment by CHERTS** [comment]
Скорее всего у Вас либо не прописаны путь до mingw в переменной Path, либо путь до компилятора C:\Espressif\xtensa-lx106-elf\

Запустите C:\Espressif\utils\ESP8266\console.bat , который в свою очередь вызовет udkvars.bat и он установит все нужные пути, естественно если у вас установлен mingw, потом сможете перейти в каталог любого примера и выполнить make
