### ISSUE TITLE
porting from esp-open-sdk

### ISSUE THREAD

**Issue by workaholic2002x** [CHERTS/esp8266-devkit#46]
esp-open-sdk has its own set-up. I am wonder, if we can port some code from esp-open-sdk to unofficial-sdk which is much cleaner for windows.
More specifically I am trying to build https://github.com/martin-ger/esp_wifi_repeater But failing. If you please help, that would be great.

**Comment by cherts** [comment]
Hi, the esp_wifi_repeater project is very difficult to adapt for build in DevKit, it uses the binary library liblwip_open_napt.a source code, not attached to the project.
