### ISSUE TITLE
NodeMCU ESP8266 Example Flashing

### ISSUE THREAD

**Issue by dragon1393** [CHERTS/esp8266-devkit#51]
Hello SIr,
I am facing problem in executing the example project I have compiled the smart_config project from example and it compiled successfully with SDK2.2.
And it generated two file
Generate eagle.flash.bin and eagle.irom0text.bin successully in folder firmware
eagle.flash.bin-------->0x00000
eagle.irom0text.bin---->0x10000
And it successfully flashed in development board but its not behaving as expected as it to be.
On serial monitor its shows it continuously resetting itself.

load 0x40100000, len 30156, room 16
tail 12
chksum 0xd0
ho 0 tail 12 room 4
load 0x3ffe8000, len 2984, room 12
tail 12
chksum 0x29
ho 0 tail 12 room 4
load 0x3ffe8bb0, len 3840, room 12
tail 4
chksum 0x31
csum 0x31
rf_cal[0] !=0x05,is 0x00
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

Please help me out to sort this.
Thanks

**Comment by cherts** [comment]
Hi,

Unofficial Development Kit for Espressif ESP8266 version 2.2.2 (24.04.2017) not supported Espressif NONOS SDK v2.2.

Only support Espressif NONOS SDK v2.1.0 (17_05_05)
