### ISSUE TITLE
Values wrong

### ISSUE THREAD

**Issue by scargill** [CHERTS/esp8266-devkit#6]
Hi

I THINK you have a line wrong in user_c - 
I believe

    console_printf("Pressure: %d.%d mbar\r\n", (int)(pressure), (int)(pressure%100));

should be 

    console_printf("Pressure: %d.%d mbar\r\n", (int)(pressure/100), (int)(pressure%100));

Also the Altitude output  - something wrong there as I am near sea level and with the pressure and temperature showing correctly - I get a very strange value for altitude - I've no idea what it is supposed to mean.

**Comment by CHERTS** [comment]
What an example of this error?

**Comment by CHERTS** [comment]
Fixed, see commit https://github.com/CHERTS/esp8266-devkit/commit/4ea529c049140585d2e028e30e8180fb6943050f
