### ISSUE TITLE
ESP8266_Relay_Board not reliable

### ISSUE THREAD

**Issue by bobricius** [CHERTS/esp8266-devkit#7]
I am not sure, example is compiled and flashed without problem.
Program runig, I see responses on terminal.
But connection is very unreliable, sometime I connect, sometime not, I try many modules, testing few weeks but I can not found problem.

**Comment by CHERTS** [comment]
I am not the author of example ESP8266_Relay_Board, the official repository of this example is [here](https://github.com/mharizanov/ESP8266_Relay_Board)
