### ISSUE TITLE
Patch for SDK_v1.2.0

### ISSUE THREAD

**Issue by fvpalha** [CHERTS/esp8266-devkit#8]
Hi Cherts.

I updated my devkit to version 2.0.7 and I applied the patch:
SDRAM Optimization Patch for SDK_v1.2.0
http://bbs.espressif.com/viewtopic.php?f=5&t=734

I saved 7 KBytes with this patch.

Best regards.

**Comment by fvpalha** [comment]
Patch for SSL based on SDK_v1.2.0
http://bbs.espressif.com/viewtopic.php?f=5&t=708

**Comment by CHERTS** [comment]
This patch will be included in version 2.0.8, its output is planned for this weekend.

**Comment by fvpalha** [comment]
Thanks @CHERTS . Congratulations.
